@startuml
'https://plantuml.com/component-diagram

entity FileContent {
* id : string
* remoteKey : string
* uploadId : string
remotePath : string
desc : string
status : int

--
* createAt : string
* createBy : string
* updatedAt : string
}

@enduml
